name: deploy-vercel

on:
  push:
    branches: [ master ] # master 分支有 push 时触发
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md

jobs:

  deploy:
    if: github.repository == 'dompling/boxjs.react'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "16.20.0"

      - run: npm install -g yarn # 安装依赖

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install # 安装依赖

      - name: Build
        id: build
        run: yarn build:vercel # 打包

      - name: Vercel
        uses: amondnet/vercel-action@v25 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.DEPLOY }} # Optional
          vercel-args: '--prod' # Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  # Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} # Required
          working-directory: dist